### ISSUE TITLE
CSS in the Stats HTML template gets mangled

### ISSUE THREAD

**Issue by iandol** [tinyproxy/tinyproxy#108]
You use {...} for your template language, but { } is also used by CSS. So in your default template:

```css
th, td
{
  text-align: left;
  padding: 0.5em;
  border: 3px solid red;
}

```

gets mangled to become 
```css
th, td
  text-align: left;
  padding: 0.5em;
  border: 3px solid red;
}

```

all you need to do is ensure the open and close {} are on the same line without newlines inbetween or some other simple rule.
