### ISSUE TITLE
Not connecting to websites via Internet Explorer and Microsoft Edge

### ISSUE THREAD

**Issue by mouzzampk2014** [tinyproxy/tinyproxy#334]
Hi, I have `tinyproxy` setup via `transmissionvpn `but I am unable connect to any website when I set up proxy on Edge and Internet Explorer but Firefox is perfectly fine. 

Any solution please?

Thank you so much

**Comment by rofl0r** [comment]
does it work without vpn stuff ?

**Comment by mouzzampk2014** [comment]
Basically `transmissionvpn` setup with vpn. Let me quickly setup `tinyproxy `image separately.

Thank you

**Comment by mouzzampk2014** [comment]
Hi, apologise for little late reply. I just tested with this compose and I can access the websites.
```
  tinyproxy:
    image: kalaksi/tinyproxy
    restart: unless-stopped
    cap_drop:
      - ALL
    ports:
      - 8888:8888
    environment:
      DISABLE_VIA_HEADER: 'yes'
      STAT_HOST: tinyproxy.stats
      MAX_CLIENTS: 100
      MIN_SPARE_SERVERS: 50
      MAX_SPARE_SERVERS: 100
      ALLOWED_NETWORKS: 192.168.1.0/24
```
Not sure why not with VPN. Any ideas?

Thank you
