### ISSUE TITLE
Tinyproxy deployed on Azure AKS

### ISSUE THREAD

**Issue by rrathord1885** [tinyproxy/tinyproxy#381]
Hi Team,
we have deployed  tinyproxy services on Azure Kubernets service and in deployment services one load balancer is attached with service. we have run 10 pods. but when we trying to access this proxy service. it is returning 1 static ip. but we expecting 10 rotating  Ips .but we are getting 1 ips in every session.
Can someone assist on it that proxy solution will work on AKS?

Thanks,
Sanjeev Singh

**Comment by ljluestc** [comment]
1. Deploy Tinyproxy in Kubernetes
First, ensure your Tinyproxy deployment is set up to scale to 10 replicas:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
spec:
  replicas: 10  # Deploy 10 instances
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      containers:
      - name: tinyproxy
        image: banacorn/tinyproxy  # or your preferred Tinyproxy image
        ports:
        - containerPort: 8888  # Default Tinyproxy port
```

2. Service Configuration
Instead of using a standard LoadBalancer service, which would give you one static external IP, you can use a NodePort service in combination with an Ingress or manage the external traffic through Azure's Load Balancer with specific configurations for IP rotation:

NodePort Service with External IP Management
```
apiVersion: v1
kind: Service
metadata:
  name: tinyproxy-service
spec:
  type: NodePort
  selector:
    app: tinyproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 30080  # Or any available node port in the range 30000-32767
```
